# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='imagelink',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
