# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0002_join_imagelink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='imagelink',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='join',
            name='ftsquared',
            field=models.IntegerField(null=True),
        ),
    ]
