# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0004_auto_20160713_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='created_at',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='join',
            name='parent_neighborhood',
            field=models.CharField(max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='join',
            name='source',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='area',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='nid',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='parentarea',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='source',
            field=models.CharField(max_length=40),
        ),
    ]
