# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0005_auto_20160714_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('pageshist', models.CharField(max_length=500, null=True)),
                ('alerthist', models.CharField(max_length=500, null=True)),
                ('searchhist', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='latitude',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='longitude',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
