# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0006_auto_20160719_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='hashid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
