# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0007_neighborhood_hashid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userhistory',
        ),
    ]
