# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0009_neighborhood_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='updated',
            field=models.NullBooleanField(default=False),
        ),
    ]
