# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0010_auto_20160721_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='score',
            field=models.FloatField(default=0, null=True),
        ),
    ]
