# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0011_join_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userhist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('pageshist', models.CharField(max_length=500, null=True)),
                ('alerthashid', models.BigIntegerField(null=True)),
                ('searchhist', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Userhistory',
        ),
    ]
