# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0013_auto_20160726_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhist',
            name='alerthist',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userhist',
            name='userid',
            field=models.BigIntegerField(max_length=20),
        ),
    ]
