# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0015_auto_20160727_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhist',
            name='pageshist',
        ),
        migrations.AddField(
            model_name='userhist',
            name='savehist',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userhist',
            name='seenhist',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userhist',
            name='alerthist',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userhist',
            name='searchhist',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
