# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0019_join_available_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='linkurl',
            new_name='url',
        ),
    ]
