# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0020_auto_20160805_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='bathroom',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='join',
            old_name='bedroom',
            new_name='bedrooms',
        ),
    ]
