# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0021_auto_20160805_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='created_at',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
