# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0022_auto_20160808_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='bathrooms',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='join',
            name='listing_type_text',
            field=models.CharField(default='Apartment', max_length=19),
        ),
    ]
