# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0023_auto_20160808_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='join',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
